language: ruby
rvm:
  - 2.1.3
env:
  - twilio_account_sid=asdf twilio_auth_token=asdf nb_nation_name=asdf nb_api_token=asdf
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
