# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 192f6392ffeeb1add526a1ecd254db3495ceafd1f1c74c8324285d87ba838fabc1fc0cc892a4917a5aad323774e3c1a1b2df0df18a8400ab60c75bf917342eb4
  twilio_account_sid: SOME_SID
  twilio_auth_token: SOME_TOKEN
  nb_nation_name: NATION_NAME
  nb_api_token: API_TOKEN

test:
  secret_key_base: 2b5c87fa71f8cfe598f41e93cf67a28b36283097d71a576ef42ba3d81b6f1850e9cc867f7e9680feddc28662524dce9ba4eb22ce8943b558d1923f17fd19d121
  twilio_account_sid: SOME_SID
  twilio_auth_token: SOME_TOKEN
  nb_nation_name: NATION_NAME
  nb_api_token: API_TOKEN

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base:    <%= ENV["SECRET_KEY_BASE"] %>
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token:  <%= ENV["TWILIO_AUTH_TOKEN"] %>
  nb_nation_name:     <%= ENV["NB_NATION_NAME"] %>
  nb_api_token:       <%= ENV["NB_API_TOKEN"] %>

